import "@/app/assets/styles/globals.css";
import Providers from "@/app/components/providers.jsx";
import cn from "@/functions/cn";
import { Inter } from "next/font/google";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
	return (
		<html lang="tr" className="dark" translate="no">
			<body className={cn("flex flex-col", inter.className, inter.style)} suppressHydrationWarning>
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	);
}
